### ISSUE TITLE
auth0_connection property options.password_dictionary.enable 400 bad request

### ISSUE THREAD

**Issue by icadariu-talend** [alexkappa/terraform-provider-auth0#183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "auth0_connection" "connection" {
  name                 = "my-example"
  is_domain_connection = false
  strategy             = "auth0"


  options {
    password_no_personal_info {
      enable = false
    }
    password_dictionary {
      enable = false
    }
    password_history {
      enable = false
      size   = 5
    }
    password_complexity_options {
      min_length = 8
    }
  }
}
```

### Debug Output

```hcl

Error: 400 Bad Request: Payload validation error: 'Expected type boolean but found type null' on property options.password_dictionary.enable.

  on auth0_connections.tf line 5, in resource "auth0_connection" "connection":
   5: resource "auth0_connection" "connection" {

```

### Expected Behavior

* continue with the execution

### Actual Behavior

* Receive Bad request. If I configure all of `password_dictionary`, `password_history` or `password_no_personal_info` to `enable = true`, code runs fine

### Steps to Reproduce

1. `terraform apply`

### References

* While searching in the documentation I've noticed that there is a typo also in - https://www.terraform.io/docs/providers/auth0/r/connection.html#password-dictionary  `password` being typed with triple `s`
```Password Dictionary

passsword_dictionary supports the following arguments:
```
* #0000

**Comment by alexkappa** [comment]
Hi @icadariu-talend what version of the provider are you using?

**Comment by icadariu-talend** [comment]
I was using a very old version -  `0.5.1`. I am sorry for not checking this in the first place :(

Now this issue is gone, but it seems I will need to deal with other issues:
- I have tried to use `debug = true` on the auth0 provider but it doesn't seem to increase verbosity.

```
STDERR:

Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
```

I will try to see if it's something wrong with my code after upgrading to 0.7.0 version.

**Comment by icadariu-talend** [comment]
@alexkappa  Here is the debug message from terraform using TF_LOG=debug

```txt
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: GET /api/v2/tenants/settings HTTP/1.1
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Host: my-tenant.my-domain.auth0.com
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: User-Agent: Go-Auth0-SDK/v3; Terraform/1.7.0
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Content-Length: 5
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Content-Type: application/json
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Accept-Encoding: gzip
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: null
2020-03-24T14:32:55.556+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: 2020/03/24 14:32:56
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: HTTP/2.0 200 OK
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Cache-Control: no-cache
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Content-Type: application/json; charset=utf-8
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Date: Tue, 24 Mar 2020 13:32:56 GMT
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Server: nginx
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Strict-Transport-Security: max-age=15724800
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: Vary: origin,accept-encoding
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: X-Ratelimit-Limit: 50
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: X-Ratelimit-Remaining: 49
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: X-Ratelimit-Reset: 1585056777
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: X-Robots-Tag: noindex, nofollow, nosnippet, noarchive
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: {"enabled_locales":["en"],"flags":{"allow_changing_enable_sso":false,"enable_client_connections":true,"enable_sso":true,"enable_mgmt_api_v1":true,"enforce_client_authentication_on_passwordless_start":false},"f
riendly_name":"my-tenant","idle_session_lifetime":12,"sandbox_version":"8","session_lifetime":10,"support_email":"support@example.com","support_url":"https://example.com/","sandbox_versions_available":[]}
2020-03-24T14:32:56.184+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:
 runtime error: invalid memory address or nil pointer dereference
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19ad7c0]
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: goroutine 84 [running]:
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: github.com/terraform-providers/terraform-provider-auth0/auth0.flattenTenantChangePassword(...)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/auth0/structure_auth0_tenant.go:8
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: github.com/terraform-providers/terraform-provider-auth0/auth0.readTenant(0xc0002ca620, 0x1b939a0, 0xc000338000, 0xc0002ca620, 0x0)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/auth0/resource_auth0_tenant.go:238 +0x140
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00015fd80, 0xc00029c640, 0x1b939a0, 0xc000338000, 0xc0005704a8, 0x0, 0x0)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e008, 0x1e9fb40, 0xc0004e8210, 0xc00029c460, 0xc00000e008, 0xc0004e8210, 0xc0000ebbd0)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1be3b80, 0xc00000e008, 0x1e9fb40, 0xc0004e8210, 0xc000046720, 0x0, 0x1e9fb40, 0xc0004e8210, 0xc000418000, 0x2f5)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00040a160, 0x1eab6a0, 0xc000532a80, 0xc000160300, 0xc000096630, 0x26981b0, 0x0, 0x0, 0x0)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc00040a160, 0x1eab6a0, 0xc000532a80, 0xc000160300, 0x0)
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-03-24T14:32:56.186+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00015c060, 0xc00040a160, 0x1eab6a0, 0xc000532a80, 0xc000160300)
2020-03-24T14:32:56.187+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-03-24T14:32:56.187+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-24T14:32:56.187+0100 [DEBUG] plugin.terraform-provider-auth0_v0.7.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-auth0/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020/03/24 14:32:56 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/03/24 14:32:56 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020-03-24T14:32:56.188+0100 [DEBUG] plugin: plugin process exited: path=/Users/myuser/redacted/terraform/update_tenant/.terraform/plugins/darwin_amd64/terraform-provider-auth0_v0.7.0_x4 pid=90288 error="exit status 2"
2020-03-24T14:32:56.267+0100 [DEBUG] plugin.terraform-provider-aws_v2.52.0_x4: 2020/03/24 14:32:56 [DEBUG] [aws-sdk-go] DEBUG: Response sts/GetCallerIdentity Details:
```

**Comment by alexkappa** [comment]
Please try using the v0.8.0 release that was published today. There was a bug that was reported yesterday on tenants. That might do it for you.

**Comment by icadariu-talend** [comment]
Hey Alex, so running the same code that works on `v0.5.1`(of course while commenting out password_no_personal_info,etc)  now returns:

```2020-03-24T20:14:38.980+0100 [DEBUG] plugin.terraform-provider-auth0_v0.8.0_x4: 2020/03/24 20:14:38 [WARN] unexpected type cty.List(cty.Object(map[string]cty.Type{"length":cty.Number, "time_step":cty.Number})) for map in json state
2020/03/24 20:14:38 [ERROR] <root>: eval: *terraform.EvalReadState, err: missing expected [
2020/03/24 20:14:38 [ERROR] <root>: eval: *terraform.EvalSequence, err: missing expected [

Error: missing expected [
```

**Comment by alexkappa** [comment]
You might want to have a look at the solution mentioned here #157 .

**Comment by icadariu-talend** [comment]
Thanks, removing totp from the state file fixed the issue. 
https://github.com/alexkappa/terraform-provider-auth0/issues/157#issuecomment-603440102
