### ISSUE TITLE
panic while using new version of provider

### ISSUE THREAD

**Issue by yinzara** [alexkappa/terraform-provider-auth0#364]
### Description

When upgrading to the most recent version of the provider, I received a panic during a terraform plan that crashed the provider

### Terraform Version
0.12
Running most recent version from master

### Affected Resource(s)

* auth0_connection

### Actual Behavior

panic during terraform plan

### Panic Output

```
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: panic: interface conversion: interface is nil, not interface {}
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: goroutine 153 [running]:
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: github.com/alexkappa/terraform-provider-auth0/auth0.connectionSchemaUpgradeV1(0xc0007fc600, 0x1c6eee0, 0xc0002e38c0, 0xc0007fc600, 0x0, 0x0)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/github/terraform-provider-auth0/auth0/resource_auth0_connection.go:675 +0x43a
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).upgradeJSONState(0xc000796008, 0x0, 0xc0007fc600, 0xc0000bf440, 0xc0007eaff0, 0x0, 0x0)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:395 +0xb7
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).UpgradeResourceState(0xc000796008, 0x1f729d0, 0xc0004cce40, 0xc0008d9200, 0xc000796008, 0xc0004cce40, 0xc0005b1ba0)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:270 +0x28f
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x1d3b5e0, 0xc000796008, 0x1f729d0, 0xc0004cce40, 0xc00081f5c0, 0x0, 0x1f729d0, 0xc0004cce40, 0xc000ed4000, 0xb0d)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/tfplugin5/tfplugin5.pb.go:3233 +0x214
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000181c0, 0x1f7ca18, 0xc0006c3200, 0xc0000c9200, 0xc00083a780, 0x25bb7e0, 0x0, 0x0, 0x0)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1180 +0x52b
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: google.golang.org/grpc.(*Server).handleStream(0xc0000181c0, 0x1f7ca18, 0xc0006c3200, 0xc0000c9200, 0x0)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1503 +0xd0c
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008341c0, 0xc0000181c0, 0x1f7ca18, 0xc0006c3200, 0xc0000c9200)
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:843 +0xab
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-04T21:48:17.308-0700 [DEBUG] plugin.terraform-provider-auth0: 	/Users/yinzara/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd
2021-04-04T21:48:17.311-0700 [DEBUG] plugin: plugin process exited: path=/Users/yinzara/.terraform.d/plugins/terraform-provider-auth0 pid=32447 error="exit status 2"
```
### Fix

I was able to fix this by changing line 671 of resource_auth0_connection from:
```
if !ok {
```
to
```
if !ok || v == nil {
```

I will submit a PR

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by leahein** [comment]
Is anyone working on this issue? If not, happy to make a PR for it.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/30 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
