### ISSUE TITLE
auth0_connection resource fails to apply when there are `scopes` 

### ISSUE THREAD

**Issue by juandiegocastrillon** [alexkappa/terraform-provider-auth0#484]
### Description

When an auth0_connection resource is changing and it has `scopes` defined, there is an error. When the resource is not being changed, the apply works correctly.

### Terraform Version

```
Terraform v1.0.10
+ provider.auth0 v0.21.1
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "google" {
  name                 = "google-oauth2"
  is_domain_connection = false
  realms = [
    "google-oauth2",
  ]
  strategy = "google-oauth2"
  enabled_clients = [(redacted list)]
  options {
    client_id     = var.google_connection_client_id
    client_secret = var.google_connection_client_secret
    scopes        = ["email", "profile"]
  }
}
```

### Expected Behavior

Changes are applied correctly.

### Actual Behavior

Plugin crashes

### Steps to Reproduce

1. `terraform apply`

### Panic Output

```
Stack trace from the terraform-provider-auth0_v0.21.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf2c9ff]

goroutine 38 [running]:
github.com/alexkappa/terraform-provider-auth0/auth0.expandConnectionOptionsScopes(0x1394328, 0xc0002d55a0, 0x1382130, 0xc0008e9400)
github.com/alexkappa/terraform-provider-auth0/auth0/structure_auth0_connection.go:680 +0x1df
github.com/alexkappa/terraform-provider-auth0/auth0.expandConnectionOptionsGoogleOAuth2(0x1394328, 0xc0002d55a0, 0xc0000a1000)
github.com/alexkappa/terraform-provider-auth0/auth0/structure_auth0_connection.go:416 +0x2bd
github.com/alexkappa/terraform-provider-auth0/auth0.expandConnection.func1(0x1394328, 0xc0002d55a0)
github.com/alexkappa/terraform-provider-auth0/auth0/structure_auth0_connection.go:297 +0x75f
github.com/alexkappa/terraform-provider-auth0/auth0.(*list).Elem(0xc0008c32c0, 0xc0002d5580)
github.com/alexkappa/terraform-provider-auth0/auth0/resource_data.go:308 +0x4d
github.com/alexkappa/terraform-provider-auth0/auth0.expandConnection(0x13946e8, 0xc0004bd180, 0xffffffffffffffff)
github.com/alexkappa/terraform-provider-auth0/auth0/structure_auth0_connection.go:292 +0x522
github.com/alexkappa/terraform-provider-auth0/auth0.updateConnection(0xc0004bd180, 0x1085b40, 0xc0004be000, 0x24, 0x1a14080)
github.com/alexkappa/terraform-provider-auth0/auth0/resource_auth0_connection.go:736 +0x3b
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000431680, 0xc000779720, 0xc000775380, 0x1085b40, 0xc0004be000, 0x1034501, 0xc000866ab8, 0xc000547b30)
github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:316 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000586280, 0xc0005e5a38, 0xc000779720, 0xc000775380, 0xc0002a5948, 0xc0005499d0, 0x10368a0)
github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e7d8, 0x138d0b0, 0xc000146930, 0xc0004bc4d0, 0xc00000e7d8, 0xc000146930, 0xc000771ba0)
github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1154380, 0xc00000e7d8, 0x138d0b0, 0xc000146930, 0xc0007a4900, 0x0, 0x138d0b0, 0xc000146930, 0xc00014b500, 0x1380)
github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000573880, 0x1396f38, 0xc0000b9800, 0xc0000e0900, 0xc0001c84e0, 0x19d24c0, 0x0, 0x0, 0x0)
google.golang.org/grpc@v1.31.1/server.go:1180 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000573880, 0x1396f38, 0xc0000b9800, 0xc0000e0900, 0x0)
google.golang.org/grpc@v1.31.1/server.go:1503 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000036210, 0xc000573880, 0x1396f38, 0xc0000b9800, 0xc0000e0900)
google.golang.org/grpc@v1.31.1/server.go:843 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd

Error: The terraform-provider-auth0_v0.21.1 plugin crashed!
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by juandiegocastrillon** [comment]
Upgrading to v0.24.3 fixed this! Somewhere along the line the `Diff` method was modified and this was fixed.
